# Generated by Django 3.0.6 on 2020-08-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepost',
            name='image',
            field=models.ImageField(default=None, upload_to='product_img/'),
        ),
    ]
