# Generated by Django 3.0.6 on 2020-08-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_messagepost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepost',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
