# Generated by Django 3.0.6 on 2020-08-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_messagepost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepost',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
