# Generated by Django 3.0.6 on 2020-08-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200822_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepost',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messagepost',
            name='userpost',
            field=models.TextField(default=None, null=True),
        ),
    ]
